In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("banana_quality_dataset.csv")

In [3]:
df.head()

,sample_id,variety,region,quality_score,quality_category,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,harvest_date,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
0,1,Manzano,Colombia,1.88,Processing,2.11,Turning,16.83,3.53,21.44,146.92,2023-10-16,13.7,58.2,2440.5,183.6
1,2,Plantain,Guatemala,2.42,Processing,4.25,Ripe,16.73,4.09,26.11,160.48,2023-10-14,5.1,280.2,2374.6,109.8
2,3,Burro,Ecuador,3.57,Premium,6.24,Overripe,21.34,1.63,25.20,225.27,2023-09-08,17.7,1246.9,1191.5,147.7
3,4,Manzano,Ecuador,2.21,Processing,5.39,Ripe,16.75,3.31,13.08,137.80,2023-10-07,13.0,1150.2,2845.1,92.8
4,5,Red Dacca,Ecuador,2.35,Processing,5.84,Ripe,16.90,3.07,12.98,227.84,2023-10-02,4.8,526.0,2136.9,129.7

In [4]:
df.tail()

,sample_id,variety,region,quality_score,quality_category,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,harvest_date,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
995,996,Burro,Ecuador,3.50,Good,4.94,Ripe,21.06,2.49,27.95,196.35,2023-10-04,12.4,409.7,2029.9,173.0
996,997,Cavendish,Philippines,2.38,Processing,6.74,Overripe,16.10,2.00,12.39,165.55,2023-09-23,14.0,314.3,1330.7,180.5
997,998,Plantain,Ecuador,1.68,Processing,1.41,Green,17.17,2.28,16.56,210.08,2023-10-19,18.4,683.0,2955.4,189.9
998,999,Fehi,Guatemala,2.02,Processing,1.34,Green,17.03,2.88,26.31,162.50,2023-09-22,8.2,1362.7,1215.8,85.5
999,1000,Red Dacca,Ecuador,2.69,Good,2.69,Turning,21.10,1.23,21.95,105.39,2023-09-29,13.2,156.7,2863.9,51.3

In [5]:
df.drop(["sample_id","harvest_date"],axis = 1 , inplace = True)

In [6]:
y = df["quality_category"]

In [7]:
x = df.drop(["quality_category"],axis = 1)

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder , StandardScaler

ct = ColumnTransformer(transformers = [('oe',OrdinalEncoder(),[0,1,4]),
                                       ('sc',StandardScaler(),[2,3,5,6,7,8,9,10,11,12])])

In [9]:
x_transformed  = ct.fit_transform(x)
x_transformed

array([[ 5.        ,  1.        ,  3.        , ..., -1.55763199,
         0.82864078,  1.47829873],
       [ 6.        ,  4.        ,  2.        , ..., -1.03791932,
         0.71183524,  0.1009444 ],
       [ 1.        ,  3.        ,  1.        , ...,  1.2251718 ,
        -1.38516968,  0.8082849 ],
       ...,
       [ 6.        ,  3.        ,  0.        , ..., -0.09494518,
         1.7412837 ,  1.59587776],
       [ 3.        ,  4.        ,  0.        , ...,  1.49626516,
        -1.34209875, -0.35257471],
       [ 7.        ,  3.        ,  3.        , ..., -1.32703876,
         1.57910303, -0.99086087]])

In [10]:
x_transformed = pd.DataFrame(x_transformed , columns = x.columns)

In [11]:
from sklearn.feature_selection import mutual_info_classif
mf = mutual_info_classif(x_transformed,y)

In [12]:
mf = pd.Series(mf)
mf.index = x_transformed.columns
mf.sort_values(ascending = False)

ripeness_index        0.913414
ripeness_category     0.236548
quality_score         0.215860
sugar_content_brix    0.160506
length_cm             0.060949
rainfall_mm           0.027523
firmness_kgf          0.005593
region                0.000000
variety               0.000000
weight_g              0.000000
tree_age_years        0.000000
altitude_m            0.000000
soil_nitrogen_ppm     0.000000
dtype: float64

In [13]:
x.drop(["tree_age_years","weight_g","firmness_kgf","altitude_m","soil_nitrogen_ppm"],axis = 1 , inplace = True)

In [14]:
x

,variety,region,quality_score,ripeness_index,ripeness_category,sugar_content_brix,length_cm,rainfall_mm
0,Manzano,Colombia,1.88,2.11,Turning,16.83,21.44,2440.5
1,Plantain,Guatemala,2.42,4.25,Ripe,16.73,26.11,2374.6
2,Burro,Ecuador,3.57,6.24,Overripe,21.34,25.20,1191.5
3,Manzano,Ecuador,2.21,5.39,Ripe,16.75,13.08,2845.1
4,Red Dacca,Ecuador,2.35,5.84,Ripe,16.90,12.98,2136.9
...,...,...,...,...,...,...,...,...
995,Burro,Ecuador,3.50,4.94,Ripe,21.06,27.95,2029.9
996,Cavendish,Philippines,2.38,6.74,Overripe,16.10,12.39,1330.7
997,Plantain,Ecuador,1.68,1.41,Green,17.17,16.56,2955.4
998,Fehi,Guatemala,2.02,1.34,Green,17.03,26.31,1215.8
999,Red Dacca,Ecuador,2.69,2.69,Turning,21.10,21.95,2863.9

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [16]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   variety             1000 non-null   object
 1   region              1000 non-null   object
 2   quality_score       1000 non-null   float64
 3   ripeness_index      1000 non-null   float64
 4   ripeness_category   1000 non-null   object
 5   sugar_content_brix  1000 non-null   float64
 6   length_cm           1000 non-null   float64
 7   rainfall_mm         1000 non-null   float64
dtypes: float64(5), object(3)
memory usage: 62.6+ KB

In [17]:
ct = ColumnTransformer(transformers = [('oe',OrdinalEncoder(),[0,1,4]),
                                      ('sc',StandardScaler(),[2,3,5,6,7])])

In [18]:
x_train_transform = ct.fit_transform(x_train)
x_train_transform = pd.DataFrame(x_train_transform)

In [21]:
x_test_transform = ct.transform(x_test)
x_test_transform = pd.DataFrame(x_test_transform)

In [24]:
from sklearn.naive_bayes import GaussianNB
gn = GaussianNB()
gn.fit(x_train_transform,y_train)
y_pred = gn.predict(x_test_transform)
from sklearn.metrics import f1_score
f1 = f1_score(y_test,y_pred,average = 'micro')
f1

0.94

In [25]:
y_pred = gn.predict(x_train_transform)
from sklearn.metrics import f1_score
f1 = f1_score(y_train,y_pred,average = 'micro')
f1

0.9575